export const ACTION_TYPES = {
    CHANGE_PHONE: 'CHANGE_PHONE',
    CHANGE_PASSWORD: 'CHANGE_PASSWORD',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_START: "LOGIN_START",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    GET_PHOTO: 'GET_PHOTO',
    SELECTED_PAGE: 'SELECTED_PAGE',
}